# Generated by Django 3.0.4 on 2020-03-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='poem_date',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='poem_tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
