# Generated by Django 3.0.4 on 2020-03-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_auto_20200324_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='first_line',
        ),
    ]
