# Generated by Django 3.0.4 on 2020-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20200318_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_title',
            field=models.CharField(default='***', max_length=100),
        ),
    ]
