# Generated by Django 3.0.4 on 2020-03-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poem_poem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='first_line',
            field=models.CharField(default=models.CharField(default='***', max_length=100, null=True), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_title',
            field=models.CharField(default='***', max_length=100, null=True),
        ),
    ]
