# Generated by Django 3.0.4 on 2020-03-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_remove_poem_first_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='first_line',
            field=models.TextField(default=models.CharField(default='***', max_length=100, null=True), null=True),
        ),
    ]
